server:
  port: 8091

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dbdigitalhealth.ces7zq8bdaxd.us-east-1.rds.amazonaws.com/dbdigitalhealth
    username: postgres
    password: adminfiap
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect


